package cc.allape.caddyfile.documentation

val GLOBAL_DIRECTIVES = arrayOf(
    "debug",
    "http_port",
    "https_port",
    "default_bind",
    "order",
    "storage",
    "storage_clean_interval",
    "admin",
    "persist_config",
    "log",
    "grace_period",
    "shutdown_delay",
    "auto_https",
    "email",
    "default_sni",
    "fallback_sni",
    "local_certs",
    "skip_install_trust",
    "acme_ca",
    "acme_ca_root",
    "acme_eab",
    "acme_dns",
    "on_demand_tls",
    "key_type",
    "cert_issuer",
    "renew_interval",
    "cert_lifetime",
    "ocsp_interval",
    "ocsp_stapling",
    "preferred_chains",
    "servers",
    "filesystem",
    "pki",
    "events",
)

val GLOBAL_SUB_DIRECTIVES = mapOf(
    "admin" to arrayOf(
        "origins",
        "enforce_origin",
    ),
    "log" to arrayOf(
        "output",
        "format",
        "level",
        "include",
        "exclude",
    ),
    "acme_eab" to arrayOf(
        "key_id",
        "mac_key",
    ),
    "on_demand_tls" to arrayOf(
        "ask",
        "permission",
    ),
    "preferred_chains" to arrayOf(
        "root_common_name",
        "any_common_name",
    ),
    "servers" to arrayOf(
        "name",
        "listener_wrappers",
        "timeouts",
        "keepalive_interval",
        "trusted_proxies",
        "client_ip_headers",
        "metrics",
        "trace",
        "max_header_size",
        "enable_full_duplex",
        "log_credentials",
        "protocols",
        "strict_sni_host",
    ),
    "timeouts" to arrayOf(
        "read_body",
        "read_header",
        "write",
        "idle",
    ),
    "pki" to arrayOf(
        "ca",
    ),
    "ca" to arrayOf(
        "name",
        "root_cn",
        "intermediate_cn",
        "intermediate_lifetime",
        "root",
        "intermediate",
    ),
    "root" to arrayOf(
        "format",
        "cert",
        "key",
    ),
    "intermediate" to arrayOf(
        "format",
        "cert",
        "key",
    ),
    "events" to arrayOf(
        "on",
    ),
)
